# scripts\install.ps1
# Zero-friction installer for windbu.
#
# Flow:
#   1. Verify Node.js >= 20
#   2. Auto-detect Windsurf Language Server (or prompt / download)
#   3. Generate .env with random API key + dashboard password
#   4. Optional: enable autostart, create desktop shortcut
#   5. Start the server in a new window
#   6. Open dashboard in default browser
#
# Safe to re-run: preserves existing .env unless -Force is passed.

[CmdletBinding()]
param(
  [switch]$Force,
  [switch]$NoAutostart,
  [switch]$NoShortcut,
  [switch]$NoBrowser
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot

function Write-Step($msg)    { Write-Host ">> $msg" -ForegroundColor Cyan }
function Write-Ok($msg)      { Write-Host "   OK  $msg" -ForegroundColor Green }
function Write-Warn2($msg)   { Write-Host "   !   $msg" -ForegroundColor Yellow }
function Write-Fail($msg)    { Write-Host "   X   $msg" -ForegroundColor Red }

function Get-RandomKey([int]$Len) {
  $bytes = New-Object byte[] $Len
  [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
  return -join ($bytes | ForEach-Object { '{0:x2}' -f $_ })
}

function Get-RandomPassword([int]$Len = 16) {
  $alphabet = 'abcdefghijkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789'
  $bytes = New-Object byte[] $Len
  [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
  return -join ($bytes | ForEach-Object { $alphabet[$_ % $alphabet.Length] })
}

Write-Host ''
Write-Host '+------------------------------------------+' -ForegroundColor Cyan
Write-Host '|  windbu installer                        |' -ForegroundColor Cyan
Write-Host '|  local gateway for Windsurf AI           |' -ForegroundColor Cyan
Write-Host '+------------------------------------------+' -ForegroundColor Cyan
Write-Host ''

# ── 1. Node.js ────────────────────────────────────────────────
Write-Step 'Checking Node.js'
try {
  $nodeVer = (& node -e "process.stdout.write(process.versions.node)") 2>$null
  if (-not $nodeVer) { throw 'node not in PATH' }
  $major = [int]($nodeVer.Split('.')[0])
  if ($major -lt 20) {
    Write-Fail "Node.js $nodeVer is too old. Need >= 20."
    Write-Host '   Download: https://nodejs.org/en/download/'
    exit 1
  }
  Write-Ok "Node.js $nodeVer"
} catch {
  Write-Fail 'Node.js not found in PATH.'
  Write-Host '   Install from: https://nodejs.org/ (LTS recommended)'
  exit 1
}

# ── 2. Language Server ────────────────────────────────────────
Write-Step 'Detecting Windsurf Language Server'
$lsPath = ''
try {
  $lsPath = & (Join-Path $PSScriptRoot 'detect-ls.ps1') 2>$null
} catch { $lsPath = '' }

if ($lsPath) {
  Write-Ok "Found: $lsPath"
} else {
  Write-Warn2 'Windsurf Language Server not found in standard locations.'
  Write-Host ''
  Write-Host '   Options:'
  Write-Host '     [1] Download automatically (~170 MB, recommended)'
  Write-Host '     [2] Enter path to an existing language_server_windows_x64.exe'
  Write-Host '     [3] Skip for now (dashboard will work, chat will not)'
  Write-Host '     [4] Cancel install'
  $choice = Read-Host '   Choose [1/2/3/4]'
  switch ($choice) {
    '1' {
      try {
        $lsPath = & (Join-Path $PSScriptRoot 'download-ls.ps1') 2>&1 |
          Where-Object { $_ -is [string] -and $_ -match '\.exe$' } |
          Select-Object -Last 1
        if (-not $lsPath -or -not (Test-Path -LiteralPath $lsPath)) {
          Write-Fail 'Auto-download failed. Run scripts\download-ls.ps1 -Force and check the error.'
          exit 1
        }
        Write-Ok "Downloaded: $lsPath"
      } catch {
        Write-Fail "Auto-download failed: $_"
        exit 1
      }
    }
    '2' {
      $manual = Read-Host '   Full path to language_server_windows_x64.exe'
      $manual = $manual.Trim('"', "'")
      if (Test-Path -LiteralPath $manual -PathType Leaf) {
        $lsPath = (Resolve-Path -LiteralPath $manual).Path
        Write-Ok "Using: $lsPath"
      } else {
        Write-Fail "File not found: $manual"
        exit 1
      }
    }
    '3' {
      Write-Warn2 'Skipping LS. Set LS_BINARY_PATH in .env later.'
      $lsPath = ''
    }
    default {
      Write-Host '   Install cancelled.'
      exit 1
    }
  }
}

# ── 3. .env generation ────────────────────────────────────────
Write-Step 'Generating .env'
$envPath = Join-Path $root '.env'
if ((Test-Path -LiteralPath $envPath) -and -not $Force) {
  Write-Warn2 '.env already exists — kept. Pass -Force to regenerate.'
  $envText = Get-Content -LiteralPath $envPath -Raw
  $apiKey = if ($envText -match 'API_KEY=(\S+)')            { $matches[1] } else { '' }
  $dashPw = if ($envText -match 'DASHBOARD_PASSWORD=(\S+)') { $matches[1] } else { '' }
  $port   = if ($envText -match 'PORT=(\d+)')               { [int]$matches[1] } else { 20129 }
} else {
  $apiKey = "sk-windbu-" + (Get-RandomKey 16)
  $dashPw = Get-RandomPassword 16
  $port = 20129
  # .env reader handles backslashes fine — no escaping needed

  @"
# windbu configuration (generated by install.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm'))

PORT=$port
HOST=127.0.0.1
API_KEY=$apiKey
DASHBOARD_PASSWORD=$dashPw
LS_BINARY_PATH=$lsPath
LS_PORT=42100
DEFAULT_MODEL=claude-sonnet-4.6
MAX_TOKENS=8192
LOG_LEVEL=info
CODEIUM_API_URL=https://server.self-serve.windsurf.com
"@ | Set-Content -LiteralPath $envPath -Encoding utf8
  Write-Ok ".env written: $envPath"
}

# Persist credentials so user can find them again
$credDir = Join-Path $env:USERPROFILE '.windbu'
$null = New-Item -ItemType Directory -Path $credDir -Force -ErrorAction SilentlyContinue
$credPath = Join-Path $credDir 'credentials.txt'
@"
windbu credentials — generated $(Get-Date -Format 'yyyy-MM-dd HH:mm')

Dashboard:  http://127.0.0.1:$port/dashboard
Password:   $dashPw

API base:   http://127.0.0.1:$port/v1
API key:    $apiKey
"@ | Set-Content -LiteralPath $credPath -Encoding utf8
Write-Ok "Credentials saved: $credPath"

# Copy API key to clipboard for immediate paste into client config
try { Set-Clipboard -Value $apiKey; Write-Ok 'API key copied to clipboard' } catch {}

# ── 4. Desktop shortcut ───────────────────────────────────────
if (-not $NoShortcut) {
  Write-Step 'Creating desktop shortcut'
  $desktop = [Environment]::GetFolderPath('Desktop')
  $lnkPath = Join-Path $desktop 'windbu.lnk'
  $icon = Join-Path $root 'assets\icon.ico'
  $shell = New-Object -ComObject WScript.Shell
  $lnk = $shell.CreateShortcut($lnkPath)
  $lnk.TargetPath = 'powershell.exe'
  $startPs1 = Join-Path $PSScriptRoot 'start.ps1'
  $lnk.Arguments = "-NoLogo -NoProfile -ExecutionPolicy Bypass -File `"$startPs1`""
  $lnk.WorkingDirectory = $root
  if (Test-Path -LiteralPath $icon) { $lnk.IconLocation = $icon }
  $lnk.Description = 'windbu — local gateway for Windsurf AI'
  $lnk.Save()
  Write-Ok "Shortcut: $lnkPath"
}

# ── 5. Autostart ──────────────────────────────────────────────
if (-not $NoAutostart) {
  Write-Step 'Autostart'
  $ans = Read-Host '   Launch windbu automatically on login? [Y/n]'
  if ([string]::IsNullOrWhiteSpace($ans) -or $ans -eq 'y' -or $ans -eq 'Y') {
    & (Join-Path $PSScriptRoot 'enable-autostart.ps1') | Out-Null
    Write-Ok 'Autostart enabled'
  } else {
    Write-Ok 'Autostart skipped (run enable-autostart.ps1 later if you change your mind)'
  }
}

# ── 6. Launch ─────────────────────────────────────────────────
Write-Step 'Starting windbu'
$startPs1 = Join-Path $PSScriptRoot 'start.ps1'
Start-Process powershell.exe -ArgumentList @(
  '-NoLogo','-NoProfile','-ExecutionPolicy','Bypass','-File', "`"$startPs1`""
) -WorkingDirectory $root | Out-Null
Start-Sleep -Seconds 3

# Probe /health so we confirm it actually came up
$healthy = $false
for ($i = 0; $i -lt 15; $i++) {
  try {
    $h = Invoke-RestMethod -Uri "http://127.0.0.1:$port/health" -TimeoutSec 2
    if ($h.status -eq 'ok') { $healthy = $true; break }
  } catch {}
  Start-Sleep -Milliseconds 500
}
if ($healthy) {
  Write-Ok "Server is up"
} else {
  Write-Warn2 "Server did not respond to /health within 10s. Check the spawned window for errors."
}

# ── 7. Browser ────────────────────────────────────────────────
if (-not $NoBrowser -and $healthy) {
  Start-Process "http://127.0.0.1:$port/dashboard" | Out-Null
}

# ── 8. First-token prompt + live verify ───────────────────────
if ($healthy) {
  Write-Host ''
  Write-Step 'Add your first Windsurf token (optional — skip with empty input)'
  Write-Host '   Get a token here:  https://windsurf.com/editor/show-auth-token'
  Write-Host '   (it starts with "ott$" or is a long JWT)'
  Write-Host ''
  $token = Read-Host '   Paste token'
  if ($token -and $token.Trim().Length -gt 20) {
    $token = $token.Trim()
    try {
      $body = @{ token = $token } | ConvertTo-Json -Compress
      $hdrs = @{ 'Content-Type' = 'application/json' }
      $resp = Invoke-RestMethod -Uri "http://127.0.0.1:$port/auth/login" -Method Post -Headers $hdrs -Body $body -TimeoutSec 30
      if ($resp.success) {
        Write-Ok "Account added: $($resp.account.email) (id=$($resp.account.id))"

        # Live verify — send a real tiny chat request to confirm end-to-end path works.
        Write-Step 'Verifying end-to-end (sending a real test chat)'
        try {
          $chatBody = @{
            model = 'gemini-2.5-flash'
            messages = @(@{ role = 'user'; content = 'Reply with exactly: ok' })
            stream = $false
            max_tokens = 8
          } | ConvertTo-Json -Depth 5 -Compress
          $chatHdrs = @{
            'Authorization' = "Bearer $apiKey"
            'Content-Type' = 'application/json'
          }
          $chat = Invoke-RestMethod -Uri "http://127.0.0.1:$port/v1/chat/completions" -Method Post -Headers $chatHdrs -Body $chatBody -TimeoutSec 45
          $content = $chat.choices[0].message.content
          Write-Ok "Chat works. Model replied: '$($content.Trim())'"
        } catch {
          Write-Warn2 "Account added, but test chat failed: $($_.Exception.Message)"
          Write-Warn2 'This usually means the token is free-tier only. Try gemini-2.5-flash or upgrade to Pro.'
        }
      } else {
        Write-Warn2 "Token not accepted. You can add it later via the dashboard."
      }
    } catch {
      Write-Warn2 "Token registration failed: $($_.Exception.Message)"
      Write-Warn2 'Add it later via dashboard (Accounts -> Add) or scripts\add-account.ps1'
    }
  } else {
    Write-Host '   Skipped. Add tokens later via dashboard or scripts\add-account.ps1' -ForegroundColor DarkGray
  }
}

Write-Host ''
Write-Host '+------------------------------------------+' -ForegroundColor Green
Write-Host '|  windbu installed                        |' -ForegroundColor Green
Write-Host '+------------------------------------------+' -ForegroundColor Green
Write-Host ''
Write-Host "  Dashboard: http://127.0.0.1:$port/dashboard"
Write-Host "  Password:  $dashPw"
Write-Host ''
Write-Host "  API base:  http://127.0.0.1:$port/v1"
Write-Host "  API key:   $apiKey"
Write-Host '            (copied to clipboard)'
Write-Host ''
Write-Host "  Credentials saved: $credPath"
Write-Host ''
Write-Host '  Next step: add a Windsurf token to the pool.' -ForegroundColor Yellow
Write-Host '    - In dashboard: Accounts -> Add'
Write-Host '    - Or via CLI:   .\scripts\add-account.ps1 -Token ''eyJ...'''
Write-Host ''
Write-Host '  Get a token:   https://windsurf.com/editor/show-auth-token'
Write-Host ''
